language: go
go:
- 1.11.x
addons:
  apt:
    packages:
    - rpm
    - snapd
env:
  matrix:
  - PATH=/snap/bin:$PATH GO111MODULE=on
  global:
    secure: iS3G0f3dAnZ2zk3avZf6CEbX0dC/McVlBAMcXCxhVpm1RpvoG8AAAQj2aWm/Oc4mjtblkgaYIqINFIaSMNjVyQH9GDD+ON3LHDPcuX6hcjJnTDYlFRXfbiVT+cU8y50Y5BlhcNZJchVPnQYecogyBtQGBksQLeEzVsGs8VwNTPlCQLpRMqPjuxaBocwP5jruI55jHZrHg7NsI4sWaG8dBxAUo7jpx+m5XefU4XnIRAC7d+F78/LPcmMXsQzor7zlPoMJNF2lHbOV17y3X+PcEIlDnAOAbQsOHEZ3YwZLFxRUULuN+w8yezWLXAfKOjutmTUen1WEU4uu1qm5bSQnqS30hUjYLb7Vuw+pb+ZUMeIqeMYO8X2awSBzas4bvcxTz1m5uZvPAjdQxR7ioIWQCcpUJYs/GECFclk9VAWUkAQ0w56qC1s4YyuiPrikVElk9WUZ+aGjLa9zh4uNKNEAyc5X99trLOu4kESEaTD/uhPpz2wMiQuiKoKJ6tZ/Q2YhgtTeWTbL0x2xKsGifqhbzyLcGXZmIHi07M1FtVNySmnFAF3jPBJjbObYV+m+qJpP4asolquHTTJB0y4YrhiXnPEqzNLH0tE0+xlMX6UcwpUV2kroWDgZI/OCmFUCMdrTj8WoUOkBGKPylmQvM6RIsuLDfRdaM6QNij3UtmtU2KM=
install:
- go build
- curl -s https://api.github.com/repos/git-chglog/git-chglog/releases/latest | grep
  "browser_download_url.*git-chglog_linux_amd64" | cut -d ":" -f 2,3 | tr -d \" |
  wget -qi -
- chmod +x git-chglog_linux_amd64
- sudo mv git-chglog_linux_amd64 /usr/local/bin/git-chglog
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: git-chglog --output ./../CHANGELOG.md $(git describe --tags $(git rev-list
    --tags --max-count=1)) && curl -sL https://git.io/goreleaser | bash -s -- --debug
    --release-notes=./../CHANGELOG.md
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
    branch: master
snap_install:
- sudo snap install snapcraft --classic
before_snap_install:
- openssl aes-256-cbc -K $encrypted_1c4d13274fff_key -iv $encrypted_1c4d13274fff_iv
  -in snap.login.enc -out snap.login -d
